"""Curated question bank templates for all 12 units.

Each unit has grammar MCQ, vocabulary MCQ, grammar rewrite exercises,
true/false statements, rewrite-to-correct sentences, complete sentences,
and writing guiding questions. These supplement questions extracted from PDFs.
"""

GRAMMAR_BANK = {

# ============================================================
# Unit 1: Life Choices - Revision of Tenses 1
# ============================================================
1: {
    "grammar_mcq": [
        {"stem": "She .......... to the gym every morning before work.",
         "options": ["a) goes", "b) is going", "c) has gone", "d) went"]},
        {"stem": "They .......... for three hours when the rain started.",
         "options": ["a) walked", "b) had been walking", "c) were walking", "d) have walked"]},
        {"stem": "I .......... my homework before my friend arrived.",
         "options": ["a) finish", "b) finished", "c) had finished", "d) have finished"]},
        {"stem": "Look! The children .......... in the park right now.",
         "options": ["a) play", "b) are playing", "c) played", "d) have played"]},
        {"stem": "By next year, we .......... in this city for ten years.",
         "options": ["a) will live", "b) will have lived", "c) are living", "d) live"]},
        {"stem": "My father .......... as a teacher since 2005.",
         "options": ["a) works", "b) worked", "c) has worked", "d) is working"]},
        {"stem": "When I was young, I .......... to school on foot every day.",
         "options": ["a) walk", "b) walked", "c) was walking", "d) had walked"]},
        {"stem": "She .......... English fluently by the time she was twelve.",
         "options": ["a) speaks", "b) spoke", "c) was speaking", "d) had spoken"]},
        {"stem": "We .......... dinner when the phone rang last night.",
         "options": ["a) had", "b) have", "c) were having", "d) are having"]},
        {"stem": "The train .......... at 9 AM every day according to the schedule.",
         "options": ["a) leaves", "b) is leaving", "c) left", "d) has left"]},
        {"stem": "He .......... three books so far this month.",
         "options": ["a) reads", "b) read", "c) has read", "d) is reading"]},
        {"stem": "While she .......... TV, someone knocked at the door.",
         "options": ["a) watches", "b) watched", "c) was watching", "d) has watched"]},
    ],
    "vocabulary_mcq": [
        {"stem": "Making a .......... decision requires careful thinking.",
         "options": ["a) wise", "b) width", "c) wild", "d) wire"]},
        {"stem": "She had to .......... between two job offers.",
         "options": ["a) chose", "b) choice", "c) choose", "d) choosing"]},
        {"stem": "His .......... to study medicine surprised everyone.",
         "options": ["a) decide", "b) decision", "c) decisive", "d) decided"]},
        {"stem": "The students showed great .......... in completing the project.",
         "options": ["a) determine", "b) determined", "c) determination", "d) determining"]},
        {"stem": "It is important to set realistic .......... in life.",
         "options": ["a) goals", "b) roles", "c) poles", "d) holes"]},
        {"stem": "She felt a sense of .......... after finishing her degree.",
         "options": ["a) achieve", "b) achievement", "c) achievable", "d) achieving"]},
    ],
    "grammar_rewrite": [
        {"sentence": "She goes to the library every weekend.", "instruction": "use past simple"},
        {"sentence": "They are studying for the exam now.", "instruction": "use present perfect"},
        {"sentence": "He watched TV when his mother called.", "instruction": "use past continuous"},
        {"sentence": "I finish my work before 5 PM every day.", "instruction": "use future simple"},
        {"sentence": "We lived in Damascus for ten years.", "instruction": "use present perfect"},
        {"sentence": "The children play in the garden after school.", "instruction": "use past continuous"},
        {"sentence": "She has already eaten lunch.", "instruction": "use past simple"},
        {"sentence": "They will travel to Aleppo next week.", "instruction": "use present continuous for future"},
    ],
    "true_false": [
        "Making good life choices always requires professional advice.",
        "Education is one of the most important life choices a person can make.",
        "Life choices only affect the person making the decision.",
        "Setting goals helps people make better decisions in life.",
        "Young people never face difficult choices in their lives.",
        "Experience and knowledge can help people make wise decisions.",
    ],
    "rewrite_correct": [
        "She always go to school by bus every morning.",
        "They was playing football when it started to rain.",
        "He have finished his homework before dinner yesterday.",
        "We are live in this house since 2010.",
        "The students has been studying since early morning.",
    ],
    "complete_sentences": [
        "People make important choices in life such as ..........",
        "Education helps people to ..........",
        "When making a decision, it is important to consider ..........",
        "Setting goals in life helps us to ..........",
        "Young people should think carefully before ..........",
    ],
    "writing_guiding": [
        "What are the most important life choices?",
        "How do life choices affect our future?",
        "What role does education play in life choices?",
        "How can young people make better decisions?",
        "What advice would you give someone making an important decision?",
    ],
},

# ============================================================
# Unit 2: Success - Revision of Tenses 2
# ============================================================
2: {
    "grammar_mcq": [
        {"stem": "By the time we arrived, the concert ..........",
         "options": ["a) started", "b) has started", "c) had started", "d) starts"]},
        {"stem": "She .......... hard all semester, so she passed the exam easily.",
         "options": ["a) studies", "b) studied", "c) had been studying", "d) is studying"]},
        {"stem": "I .......... never .......... such a beautiful sunset before.",
         "options": ["a) had / seen", "b) have / saw", "c) did / see", "d) was / seeing"]},
        {"stem": "They .......... the project by next Friday.",
         "options": ["a) finish", "b) will finish", "c) will have finished", "d) are finishing"]},
        {"stem": "He .......... his car for two hours before it finally started.",
         "options": ["a) was repairing", "b) had been repairing", "c) repaired", "d) repairs"]},
        {"stem": "Next month, we .......... in this company for five years.",
         "options": ["a) work", "b) will work", "c) will have been working", "d) are working"]},
        {"stem": "After she .......... the letter, she posted it immediately.",
         "options": ["a) writes", "b) wrote", "c) had written", "d) was writing"]},
        {"stem": "The students .......... the exam when the bell rang.",
         "options": ["a) were still writing", "b) still wrote", "c) have still written", "d) still write"]},
        {"stem": "I .......... about calling you when you suddenly appeared.",
         "options": ["a) think", "b) thought", "c) was thinking", "d) have thought"]},
        {"stem": "She .......... three languages fluently since childhood.",
         "options": ["a) speaks", "b) spoke", "c) has spoken", "d) is speaking"]},
    ],
    "vocabulary_mcq": [
        {"stem": "Hard work and .......... are keys to success.",
         "options": ["a) dedicate", "b) dedication", "c) dedicated", "d) dedicating"]},
        {"stem": "She finally .......... her dream of becoming a doctor.",
         "options": ["a) achieved", "b) achievement", "c) achievable", "d) achieving"]},
        {"stem": "Success requires .......... and patience.",
         "options": ["a) persevere", "b) perseverance", "c) persevered", "d) persevering"]},
        {"stem": "Many successful people had to .......... many obstacles.",
         "options": ["a) overcome", "b) overlook", "c) overtake", "d) overflow"]},
        {"stem": "She is a great source of .......... for young women.",
         "options": ["a) inspire", "b) inspiration", "c) inspired", "d) inspiring"]},
        {"stem": "Failure is often a .......... stone to success.",
         "options": ["a) step", "b) stepping", "c) stepped", "d) steps"]},
    ],
    "grammar_rewrite": [
        {"sentence": "After he had finished dinner, he went for a walk.", "instruction": "begin with: He went..."},
        {"sentence": "She has been working at this company since 2018.", "instruction": "use past perfect continuous"},
        {"sentence": "They will have completed the bridge by December.", "instruction": "use future perfect"},
        {"sentence": "I was reading when the lights went out.", "instruction": "begin with: The lights..."},
        {"sentence": "We had already left when the storm started.", "instruction": "begin with: The storm..."},
        {"sentence": "She passed the test because she had studied hard.", "instruction": "begin with: Because..."},
        {"sentence": "The workers finished the building last month.", "instruction": "use past perfect"},
        {"sentence": "He has lived in London for six years.", "instruction": "use past simple"},
    ],
    "true_false": [
        "Success can only be measured by wealth and fame.",
        "Failure can teach us important lessons on the road to success.",
        "Successful people never experience setbacks or difficulties.",
        "Hard work is more important than talent for achieving success.",
        "Education always guarantees success in life.",
        "Perseverance means giving up when things get difficult.",
    ],
    "rewrite_correct": [
        "She has been work at this company for five years.",
        "By the time we arrive, the show had already started.",
        "They was studying all night for the final exam.",
        "He will has finished the report by tomorrow.",
        "I had been wait for an hour when the bus finally came.",
    ],
    "complete_sentences": [
        "Success can be defined as ..........",
        "To achieve your goals, you need to ..........",
        "Successful people often share qualities such as ..........",
        "Failure can help us succeed because ..........",
        "The most important factor in achieving success is ..........",
    ],
    "writing_guiding": [
        "What does success mean to you?",
        "What qualities do successful people have?",
        "Is failure necessary for success? Why?",
        "Who is a successful person you admire? Why?",
        "How can education contribute to success?",
    ],
},

# ============================================================
# Unit 3: Medicine - Passive Voice
# ============================================================
3: {
    "grammar_mcq": [
        {"stem": "The patient .......... by the doctor yesterday.",
         "options": ["a) examined", "b) was examined", "c) is examined", "d) has examined"]},
        {"stem": "New medicines .......... in laboratories every year.",
         "options": ["a) develop", "b) are developed", "c) developed", "d) have developed"]},
        {"stem": "The hospital .......... in 1990.",
         "options": ["a) built", "b) was built", "c) is built", "d) has been built"]},
        {"stem": "The injured people .......... to the nearest hospital right now.",
         "options": ["a) take", "b) are being taken", "c) were taken", "d) took"]},
        {"stem": "Antibiotics .......... to treat bacterial infections.",
         "options": ["a) use", "b) are used", "c) used", "d) using"]},
        {"stem": "The operation .......... successfully by the surgeon last week.",
         "options": ["a) performs", "b) performed", "c) was performed", "d) is performed"]},
        {"stem": "Many diseases .......... through vaccination in the past century.",
         "options": ["a) prevent", "b) prevented", "c) have been prevented", "d) are preventing"]},
        {"stem": "The X-ray machine .......... by Wilhelm Roentgen in 1895.",
         "options": ["a) invents", "b) invented", "c) was invented", "d) is invented"]},
        {"stem": "The patient .......... that the surgery was successful.",
         "options": ["a) told", "b) was told", "c) tells", "d) is telling"]},
        {"stem": "Traditional medicines .......... from plants and herbs.",
         "options": ["a) make", "b) are made", "c) made", "d) making"]},
        {"stem": "The blood samples .......... to the laboratory for testing.",
         "options": ["a) send", "b) are sent", "c) sent", "d) sending"]},
        {"stem": "Penicillin .......... by Alexander Fleming in 1928.",
         "options": ["a) discovers", "b) discovered", "c) was discovered", "d) is discovered"]},
    ],
    "vocabulary_mcq": [
        {"stem": "The doctor wrote a .......... for the medicine.",
         "options": ["a) prescription", "b) description", "c) subscription", "d) inscription"]},
        {"stem": "The surgeon performed a complex .......... on the patient.",
         "options": ["a) operate", "b) operation", "c) operator", "d) operating"]},
        {"stem": "Vaccines help build .......... against diseases.",
         "options": ["a) immune", "b) immunity", "c) immunize", "d) immunized"]},
        {"stem": "The .......... of a new drug takes many years of research.",
         "options": ["a) develop", "b) development", "c) developing", "d) developed"]},
        {"stem": "She went to the hospital for a medical ..........",
         "options": ["a) examine", "b) examination", "c) examiner", "d) examined"]},
        {"stem": "Modern .......... equipment helps doctors diagnose diseases accurately.",
         "options": ["a) medicine", "b) medical", "c) medicate", "d) medication"]},
    ],
    "grammar_rewrite": [
        {"sentence": "The doctor examined the patient carefully.", "instruction": "change into passive voice"},
        {"sentence": "Scientists discovered a new treatment for cancer.", "instruction": "change into passive voice"},
        {"sentence": "The nurse is preparing the medicine for the patient.", "instruction": "change into passive voice"},
        {"sentence": "They have built a new hospital in the city center.", "instruction": "change into passive voice"},
        {"sentence": "The surgeon will perform the operation tomorrow.", "instruction": "change into passive voice"},
        {"sentence": "People use herbs to treat some diseases.", "instruction": "change into passive voice"},
        {"sentence": "The ambulance was taking the injured to hospital.", "instruction": "change into passive voice"},
        {"sentence": "Researchers had tested the vaccine before releasing it.", "instruction": "change into passive voice"},
        {"sentence": "The medicine was prescribed by the doctor.", "instruction": "change into active voice"},
        {"sentence": "A cure for the disease has been found by scientists.", "instruction": "change into active voice"},
    ],
    "true_false": [
        "Modern medicine relies entirely on natural remedies and herbs.",
        "The discovery of antibiotics was a major breakthrough in medicine.",
        "Surgery was first practiced in the 20th century.",
        "Vaccination helps protect people from infectious diseases.",
        "Traditional medicine has no role in modern healthcare.",
        "X-ray imaging allows doctors to see inside the body without surgery.",
        "All diseases can be cured with modern medicine.",
        "Medical research has led to longer life expectancy worldwide.",
    ],
    "rewrite_correct": [
        "The medicine was prescribe by the doctor last week.",
        "New hospitals is being built in many cities across the country.",
        "The patient was examine by three different specialists.",
        "Antibiotics was discovered by Alexander Fleming in 1928.",
        "The injured people has been taken to the nearest hospital.",
    ],
    "complete_sentences": [
        "Modern medicine has helped humanity by ..........",
        "The discovery of antibiotics was important because ..........",
        "Vaccination protects people from diseases such as ..........",
        "In ancient times, people treated diseases using ..........",
        "Medical technology has improved in recent years, for example ..........",
    ],
    "writing_guiding": [
        "What are the most important medical discoveries in history?",
        "How has medicine changed over the centuries?",
        "What role does technology play in modern medicine?",
        "How can people stay healthy and prevent diseases?",
        "What is the importance of medical research?",
    ],
},

# ============================================================
# Unit 4: Engineering - Causative
# ============================================================
4: {
    "grammar_mcq": [
        {"stem": "I .......... my car repaired at the garage last week.",
         "options": ["a) have", "b) had", "c) get", "d) got"]},
        {"stem": "She .......... her hair cut at the salon every month.",
         "options": ["a) gets", "b) makes", "c) does", "d) lets"]},
        {"stem": "We .......... the house painted by professionals next week.",
         "options": ["a) will have", "b) will get", "c) both a and b", "d) neither a nor b"]},
        {"stem": "He .......... his suit dry-cleaned before the wedding.",
         "options": ["a) has", "b) had", "c) got", "d) made"]},
        {"stem": "They are .......... a new bridge built across the river.",
         "options": ["a) having", "b) making", "c) doing", "d) letting"]},
        {"stem": "I need to .......... my eyes tested soon.",
         "options": ["a) make", "b) do", "c) get", "d) let"]},
        {"stem": "She .......... her assistant type the report yesterday.",
         "options": ["a) had", "b) got", "c) made", "d) all of these"]},
        {"stem": "The manager .......... the employees work overtime.",
         "options": ["a) had", "b) got", "c) made", "d) let"]},
        {"stem": "He didn't fix the computer himself; he .......... it fixed.",
         "options": ["a) has", "b) had", "c) made", "d) let"]},
        {"stem": "We should .......... the roof checked before winter.",
         "options": ["a) make", "b) have", "c) do", "d) let"]},
    ],
    "vocabulary_mcq": [
        {"stem": "Civil .......... involves designing roads, bridges, and buildings.",
         "options": ["a) engineer", "b) engineering", "c) engineered", "d) engine"]},
        {"stem": "The bridge was built using advanced .......... techniques.",
         "options": ["a) construct", "b) construction", "c) constructive", "d) constructor"]},
        {"stem": "The new building design is both .......... and beautiful.",
         "options": ["a) function", "b) functional", "c) functionally", "d) functioning"]},
        {"stem": "Engineers must ensure the .......... of all structures they design.",
         "options": ["a) safe", "b) safety", "c) safely", "d) safeguard"]},
        {"stem": "The .......... of the new highway took three years.",
         "options": ["a) construct", "b) construction", "c) constructing", "d) constructed"]},
        {"stem": "Modern buildings are designed to be earthquake-.......... .",
         "options": ["a) resist", "b) resistant", "c) resistance", "d) resisting"]},
    ],
    "grammar_rewrite": [
        {"sentence": "A mechanic repaired my car.", "instruction": "rewrite using causative (have)"},
        {"sentence": "A hairdresser cut her hair.", "instruction": "rewrite using causative (get)"},
        {"sentence": "A painter will paint our house.", "instruction": "rewrite using causative (have)"},
        {"sentence": "A dentist checked his teeth.", "instruction": "rewrite using causative (have)"},
        {"sentence": "Someone delivers newspapers to our house every morning.", "instruction": "rewrite using causative (have)"},
        {"sentence": "An electrician is fixing the wiring in our office.", "instruction": "rewrite using causative (have)"},
        {"sentence": "The teacher made the students rewrite the essay.", "instruction": "rewrite using causative (make)"},
        {"sentence": "I asked someone to clean my suit.", "instruction": "rewrite using causative (get)"},
    ],
    "true_false": [
        "Engineering is only about building bridges and roads.",
        "Civil engineering is one of the oldest branches of engineering.",
        "Engineers do not need to consider environmental impact in their designs.",
        "Modern engineering uses computer-aided design (CAD) software.",
        "The construction of large buildings requires teamwork among different engineers.",
        "Earthquake-resistant buildings cannot be built with current technology.",
    ],
    "rewrite_correct": [
        "I had my car repair at the garage yesterday.",
        "She gets her hair cutting every two months.",
        "We will have the house paint by a professional.",
        "He had the mechanic fixed his bicycle last week.",
        "They are having a new swimming pool build in their garden.",
    ],
    "complete_sentences": [
        "Engineers design structures such as ..........",
        "The causative form is used when we want someone to ..........",
        "Modern engineering relies on technology like ..........",
        "Civil engineers are responsible for ..........",
        "Before building a bridge, engineers must consider ..........",
    ],
    "writing_guiding": [
        "What does an engineer do?",
        "What are the different types of engineering?",
        "Why is engineering important for society?",
        "What qualities should a good engineer have?",
        "How has technology changed engineering?",
    ],
},

# ============================================================
# Unit 5: Civil Rights - Relative Clauses
# ============================================================
5: {
    "grammar_mcq": [
        {"stem": "The man .......... lives next door is a doctor.",
         "options": ["a) which", "b) who", "c) whom", "d) whose"]},
        {"stem": "The book .......... I borrowed from the library was very interesting.",
         "options": ["a) who", "b) whom", "c) which", "d) whose"]},
        {"stem": "She is the teacher .......... class I enjoy the most.",
         "options": ["a) who", "b) which", "c) whose", "d) whom"]},
        {"stem": "The city .......... we visited last summer was beautiful.",
         "options": ["a) who", "b) whose", "c) which", "d) whom"]},
        {"stem": "The girl .......... father is a pilot wants to be an engineer.",
         "options": ["a) who", "b) which", "c) whom", "d) whose"]},
        {"stem": "That is the restaurant .......... we had dinner last night.",
         "options": ["a) which", "b) where", "c) whose", "d) who"]},
        {"stem": "The reason .......... she was late was the traffic jam.",
         "options": ["a) which", "b) where", "c) why", "d) who"]},
        {"stem": "Do you remember the day .......... we first met?",
         "options": ["a) which", "b) where", "c) who", "d) when"]},
        {"stem": "Martin Luther King Jr., .......... fought for civil rights, won the Nobel Peace Prize.",
         "options": ["a) which", "b) who", "c) whom", "d) whose"]},
        {"stem": "The speech .......... he gave inspired millions of people.",
         "options": ["a) who", "b) whose", "c) which", "d) where"]},
    ],
    "vocabulary_mcq": [
        {"stem": "Everyone should have equal .......... regardless of race or gender.",
         "options": ["a) right", "b) rights", "c) rite", "d) write"]},
        {"stem": "The civil rights movement fought against racial ..........",
         "options": ["a) discriminate", "b) discrimination", "c) discriminating", "d) discriminated"]},
        {"stem": "Freedom and .......... are basic human rights.",
         "options": ["a) equal", "b) equality", "c) equalize", "d) equalized"]},
        {"stem": "People should be treated with .......... and respect.",
         "options": ["a) dignify", "b) dignity", "c) dignified", "d) dignifying"]},
        {"stem": "The .......... protested peacefully for their rights.",
         "options": ["a) activist", "b) activists", "c) active", "d) activity"]},
        {"stem": ".......... means treating people unfairly because of their differences.",
         "options": ["a) Prejudice", "b) Justice", "c) Tolerance", "d) Freedom"]},
    ],
    "grammar_rewrite": [
        {"sentence": "The woman is a famous lawyer. She lives next door.", "instruction": "join using a relative pronoun"},
        {"sentence": "I met a man. His daughter is a famous singer.", "instruction": "join using whose"},
        {"sentence": "This is the school. I studied here as a child.", "instruction": "join using where"},
        {"sentence": "The car was very expensive. He bought it last month.", "instruction": "join using which"},
        {"sentence": "She is the activist. Her speeches inspired millions.", "instruction": "join using whose"},
        {"sentence": "That was the year. The civil rights law was passed then.", "instruction": "join using when"},
        {"sentence": "Nelson Mandela fought for freedom. He became president of South Africa.", "instruction": "join using who"},
        {"sentence": "The book talks about civil rights. I read it last week.", "instruction": "join using which"},
    ],
    "true_false": [
        "The civil rights movement only took place in the United States.",
        "Martin Luther King Jr. advocated for peaceful protest.",
        "All countries in the world guarantee equal rights for all citizens.",
        "The Universal Declaration of Human Rights was adopted in 1948.",
        "Civil rights only refer to political rights.",
        "Women's suffrage was an important part of the civil rights movement.",
    ],
    "rewrite_correct": [
        "The man which lives next door is very friendly.",
        "She is the teacher who class I enjoy the most.",
        "The book who I read was very interesting.",
        "This is the school which I studied as a child.",
        "The girl which father is a doctor wants to study medicine.",
    ],
    "complete_sentences": [
        "Civil rights are important because ..........",
        "Martin Luther King Jr. is remembered for ..........",
        "Discrimination means ..........",
        "People can fight for their rights by ..........",
        "The Universal Declaration of Human Rights states that ..........",
    ],
    "writing_guiding": [
        "What are civil rights?",
        "Who is a famous civil rights leader you know about?",
        "Why is equality important in society?",
        "How can people fight against discrimination?",
        "What civil rights issues exist today?",
    ],
},

# ============================================================
# Unit 6: United Nations - Future Forms
# ============================================================
6: {
    "grammar_mcq": [
        {"stem": "I .......... you with your project tomorrow.",
         "options": ["a) will help", "b) am helping", "c) help", "d) helped"]},
        {"stem": "Look at those clouds! It .......... rain soon.",
         "options": ["a) will", "b) is going to", "c) shall", "d) does"]},
        {"stem": "The meeting .......... at 10 AM tomorrow according to the schedule.",
         "options": ["a) will start", "b) starts", "c) is starting", "d) started"]},
        {"stem": "She .......... to Paris next week. She already has her ticket.",
         "options": ["a) will fly", "b) is flying", "c) flies", "d) flew"]},
        {"stem": "I think it .......... a good idea to join the United Nations club.",
         "options": ["a) is going to be", "b) will be", "c) is being", "d) was"]},
        {"stem": "By 2030, the UN .......... for 85 years.",
         "options": ["a) will exist", "b) will have existed", "c) exists", "d) existed"]},
        {"stem": "The plane .......... at 6 PM. It is on the timetable.",
         "options": ["a) will depart", "b) is going to depart", "c) departs", "d) departed"]},
        {"stem": "I promise I .......... late for the meeting again.",
         "options": ["a) am not being", "b) won't be", "c) am not going to be", "d) don't be"]},
        {"stem": "She is very tired. She .......... to bed early tonight.",
         "options": ["a) will go", "b) is going to go", "c) goes", "d) went"]},
        {"stem": "The UN General Assembly .......... its session next month.",
         "options": ["a) will hold", "b) holds", "c) is holding", "d) all are correct"]},
    ],
    "vocabulary_mcq": [
        {"stem": "The United Nations works to maintain international ..........",
         "options": ["a) peace", "b) piece", "c) pierce", "d) place"]},
        {"stem": "Countries that are members of the UN are called member ..........",
         "options": ["a) states", "b) stages", "c) stacks", "d) stakes"]},
        {"stem": "The UN Security Council is responsible for maintaining .......... security.",
         "options": ["a) nation", "b) national", "c) international", "d) internally"]},
        {"stem": "The organization works to protect human .......... worldwide.",
         "options": ["a) right", "b) rights", "c) rites", "d) writes"]},
        {"stem": "The UN provides humanitarian .......... to people in need.",
         "options": ["a) aid", "b) aide", "c) add", "d) ad"]},
        {"stem": "Diplomacy involves .......... between countries to resolve conflicts.",
         "options": ["a) negotiate", "b) negotiation", "c) negotiating", "d) negotiated"]},
    ],
    "grammar_rewrite": [
        {"sentence": "I will visit my grandparents next weekend.", "instruction": "use 'going to'"},
        {"sentence": "The conference is going to start at 9 AM.", "instruction": "use present simple for schedule"},
        {"sentence": "We will travel to Geneva next summer.", "instruction": "use present continuous for plan"},
        {"sentence": "She is going to study international law.", "instruction": "use 'will'"},
        {"sentence": "The train leaves at 8 PM tonight.", "instruction": "use future with 'will'"},
        {"sentence": "They are meeting the UN ambassador tomorrow.", "instruction": "use 'going to'"},
        {"sentence": "I will probably attend the conference.", "instruction": "use present continuous"},
        {"sentence": "The session starts at 10 AM on Monday.", "instruction": "use 'will'"},
    ],
    "true_false": [
        "The United Nations was established after World War I.",
        "The UN has 193 member states.",
        "The UN Security Council has five permanent members.",
        "The United Nations headquarters is located in Geneva, Switzerland.",
        "The UN works to promote peace, security, and human rights.",
        "Only large countries can be members of the United Nations.",
    ],
    "rewrite_correct": [
        "The UN will established in 1945 after World War II.",
        "She is go to study law at university next year.",
        "The meeting will starts at 10 AM tomorrow morning.",
        "They going to travel to New York for the UN session.",
        "The plane will departs at 6 PM according to the schedule.",
    ],
    "complete_sentences": [
        "The United Nations was established in order to ..........",
        "The UN Security Council is responsible for ..........",
        "Future forms in English include ..........",
        "The UN helps developing countries by ..........",
        "When we talk about scheduled events, we use ..........",
    ],
    "writing_guiding": [
        "What is the United Nations?",
        "When and why was the UN established?",
        "What are the main goals of the UN?",
        "How does the UN help maintain world peace?",
        "What role does your country play in the UN?",
    ],
},

# ============================================================
# Unit 7: Microorganisms - Conditionals II, III
# ============================================================
7: {
    "grammar_mcq": [
        {"stem": "If I .......... a doctor, I would help poor people for free.",
         "options": ["a) am", "b) was", "c) were", "d) be"]},
        {"stem": "If she had studied harder, she .......... the exam.",
         "options": ["a) would pass", "b) would have passed", "c) will pass", "d) passes"]},
        {"stem": "If they .......... the bacteria, the infection would spread.",
         "options": ["a) don't kill", "b) didn't kill", "c) hadn't killed", "d) won't kill"]},
        {"stem": "If I had known about the virus, I .......... more careful.",
         "options": ["a) would be", "b) would have been", "c) will be", "d) am"]},
        {"stem": "He would travel the world if he .......... enough money.",
         "options": ["a) has", "b) had", "c) have", "d) will have"]},
        {"stem": "If we .......... the medicine earlier, the patient would have recovered.",
         "options": ["a) gave", "b) give", "c) had given", "d) would give"]},
        {"stem": "She .......... the infection if she had washed her hands properly.",
         "options": ["a) won't get", "b) wouldn't get", "c) wouldn't have got", "d) didn't get"]},
        {"stem": "If bacteria .......... oxygen, they would die quickly.",
         "options": ["a) don't get", "b) didn't get", "c) hadn't got", "d) won't get"]},
        {"stem": "What would you do if you .......... a dangerous virus in the lab?",
         "options": ["a) find", "b) found", "c) had found", "d) will find"]},
        {"stem": "If the scientists had discovered the cure earlier, many lives ..........",
         "options": ["a) will be saved", "b) would be saved", "c) would have been saved", "d) are saved"]},
        {"stem": "If I .......... you, I would see a doctor immediately.",
         "options": ["a) am", "b) was", "c) were", "d) will be"]},
        {"stem": "The disease .......... if proper hygiene had been maintained.",
         "options": ["a) won't spread", "b) wouldn't spread", "c) wouldn't have spread", "d) doesn't spread"]},
    ],
    "vocabulary_mcq": [
        {"stem": ".......... are tiny living things that can only be seen under a microscope.",
         "options": ["a) Microorganisms", "b) Organs", "c) Organisms", "d) Minerals"]},
        {"stem": "Bacteria can cause .......... in humans and animals.",
         "options": ["a) infect", "b) infection", "c) infectious", "d) infecting"]},
        {"stem": "A .......... is a substance that kills or stops the growth of bacteria.",
         "options": ["a) antibiotic", "b) antisocial", "c) antidote", "d) antique"]},
        {"stem": "Viruses are much smaller than .......... .",
         "options": ["a) bacteria", "b) bacterial", "c) bacterium", "d) bacteriology"]},
        {"stem": "Good .......... helps prevent the spread of diseases.",
         "options": ["a) hygiene", "b) hygienic", "c) hygienist", "d) hygienically"]},
        {"stem": "The immune system helps the body fight against ..........",
         "options": ["a) disease", "b) diseases", "c) diseased", "d) diseasing"]},
    ],
    "grammar_rewrite": [
        {"sentence": "I don't have a microscope, so I can't study the bacteria.", "instruction": "use second conditional"},
        {"sentence": "She didn't take the medicine, so she didn't get better.", "instruction": "use third conditional"},
        {"sentence": "He doesn't exercise regularly, so he gets sick often.", "instruction": "use second conditional"},
        {"sentence": "They didn't wash their hands, so they caught the infection.", "instruction": "use third conditional"},
        {"sentence": "We don't have enough vaccines, so many people are still at risk.", "instruction": "use second conditional"},
        {"sentence": "She didn't see the doctor early, so her condition got worse.", "instruction": "use third conditional"},
        {"sentence": "He isn't a biologist, so he can't identify the microorganism.", "instruction": "use second conditional"},
        {"sentence": "The government didn't act quickly, so the disease spread.", "instruction": "use third conditional"},
    ],
    "true_false": [
        "All microorganisms are harmful to humans.",
        "Bacteria can be both helpful and harmful to the human body.",
        "Viruses can reproduce on their own without a host cell.",
        "Antibiotics are effective against viral infections.",
        "Some bacteria help in the digestion of food.",
        "Washing hands regularly can help prevent the spread of infections.",
        "Microorganisms can only survive in warm environments.",
        "Vaccines work by helping the body build immunity against specific diseases.",
    ],
    "rewrite_correct": [
        "If I was you, I would take the medicine immediately.",
        "If she would have studied biology, she would understand microorganisms.",
        "He wouldn't have got sick if he washed his hands properly.",
        "If they will have a microscope, they could study the bacteria.",
        "If the doctor had came earlier, the patient would have survived.",
    ],
    "complete_sentences": [
        "Microorganisms are important because ..........",
        "If scientists hadn't discovered antibiotics, ..........",
        "Bacteria differ from viruses in that ..........",
        "The immune system protects our body by ..........",
        "If I were a scientist, I would ..........",
    ],
    "writing_guiding": [
        "What are microorganisms?",
        "How do bacteria differ from viruses?",
        "What are the beneficial uses of microorganisms?",
        "How can we protect ourselves from harmful microorganisms?",
        "What would happen if antibiotics stopped working?",
    ],
},

# ============================================================
# Unit 8: Facts about Human Body - Expressing Wishes
# ============================================================
8: {
    "grammar_mcq": [
        {"stem": "I wish I .......... taller.",
         "options": ["a) am", "b) was", "c) were", "d) be"]},
        {"stem": "She wishes she .......... harder for the biology exam.",
         "options": ["a) studies", "b) studied", "c) had studied", "d) will study"]},
        {"stem": "I wish I .......... speak three languages fluently.",
         "options": ["a) can", "b) could", "c) will", "d) may"]},
        {"stem": "He wishes he .......... eaten so much food at the party.",
         "options": ["a) didn't", "b) doesn't", "c) hadn't", "d) won't"]},
        {"stem": "They wish they .......... more about the human body.",
         "options": ["a) know", "b) knew", "c) known", "d) knowing"]},
        {"stem": "I wish it .......... raining. I want to go outside.",
         "options": ["a) stops", "b) stopped", "c) would stop", "d) will stop"]},
        {"stem": "She wishes she .......... the doctor's advice yesterday.",
         "options": ["a) follows", "b) followed", "c) had followed", "d) will follow"]},
        {"stem": "We wish we .......... afford the expensive medical treatment.",
         "options": ["a) can", "b) could", "c) will", "d) are able to"]},
        {"stem": "If only I .......... about the health risks earlier!",
         "options": ["a) know", "b) knew", "c) had known", "d) will know"]},
        {"stem": "He wishes the doctor .......... him better advice.",
         "options": ["a) gives", "b) gave", "c) had given", "d) will give"]},
    ],
    "vocabulary_mcq": [
        {"stem": "The human body is made up of millions of ..........",
         "options": ["a) cells", "b) shells", "c) sells", "d) seals"]},
        {"stem": "The .......... system carries blood throughout the body.",
         "options": ["a) circular", "b) circulatory", "c) circulate", "d) circulation"]},
        {"stem": "Bones provide .......... and support for the body.",
         "options": ["a) protect", "b) protection", "c) protective", "d) protector"]},
        {"stem": "The brain is the most complex .......... in the human body.",
         "options": ["a) organ", "b) organic", "c) organism", "d) organize"]},
        {"stem": "The .......... system breaks down food into nutrients.",
         "options": ["a) digest", "b) digestive", "c) digestion", "d) digested"]},
        {"stem": "Regular exercise strengthens the .......... and bones.",
         "options": ["a) muscle", "b) muscles", "c) muscular", "d) musculature"]},
    ],
    "grammar_rewrite": [
        {"sentence": "I don't know much about the human body.", "instruction": "begin with: I wish..."},
        {"sentence": "She didn't exercise regularly, so she is not healthy.", "instruction": "begin with: She wishes..."},
        {"sentence": "He can't run fast because he doesn't train.", "instruction": "begin with: He wishes..."},
        {"sentence": "I ate too much junk food last week.", "instruction": "begin with: I wish..."},
        {"sentence": "We don't have a gym in our school.", "instruction": "begin with: We wish..."},
        {"sentence": "She didn't become a doctor.", "instruction": "begin with: She wishes..."},
        {"sentence": "They can't afford healthy organic food.", "instruction": "begin with: They wish..."},
        {"sentence": "I didn't take care of my health when I was young.", "instruction": "begin with: I wish..."},
    ],
    "true_false": [
        "The human body has 206 bones in total.",
        "The heart is located on the right side of the chest.",
        "Blood carries oxygen and nutrients to all parts of the body.",
        "The human brain uses about 20% of the body's energy.",
        "Adults have more bones than newborn babies.",
        "The skin is the largest organ in the human body.",
    ],
    "rewrite_correct": [
        "I wish I can speak English fluently.",
        "She wishes she doesn't eat so much yesterday.",
        "He wish he were taller and stronger.",
        "They wishes they had studied medicine at university.",
        "I wish I will be able to run the marathon next year.",
    ],
    "complete_sentences": [
        "The human body is amazing because ..........",
        "I wish I could .......... because ..........",
        "The circulatory system is responsible for ..........",
        "To keep our bodies healthy, we should ..........",
        "The brain controls ..........",
    ],
    "writing_guiding": [
        "What are some amazing facts about the human body?",
        "How does the human body protect itself from diseases?",
        "Why is exercise important for the body?",
        "What would you wish to change about your health habits?",
        "How can we take better care of our bodies?",
    ],
},

# ============================================================
# Unit 9: Citizenship - Paired Conjunctions
# ============================================================
9: {
    "grammar_mcq": [
        {"stem": ".......... the teacher .......... the students were present at the meeting.",
         "options": ["a) Both / and", "b) Either / or", "c) Neither / nor", "d) Not only / but also"]},
        {"stem": ".......... he studies hard, .......... he will fail the exam.",
         "options": ["a) Both / and", "b) Either / or", "c) Neither / nor", "d) Not only / but also"]},
        {"stem": "She is .......... intelligent .......... hardworking.",
         "options": ["a) either / or", "b) neither / nor", "c) both / and", "d) whether / or"]},
        {"stem": ".......... did he apologize, .......... did he try to explain.",
         "options": ["a) Both / and", "b) Either / or", "c) Neither / nor", "d) Not only / but also"]},
        {"stem": "You can .......... stay here .......... come with us. It's your choice.",
         "options": ["a) both / and", "b) either / or", "c) neither / nor", "d) not only / but also"]},
        {"stem": ".......... was the food delicious, .......... it was also affordable.",
         "options": ["a) Both / and", "b) Either / or", "c) Neither / nor", "d) Not only / but also"]},
        {"stem": "Good citizens .......... obey the law .......... respect others.",
         "options": ["a) either / or", "b) neither / nor", "c) both / and", "d) whether / or"]},
        {"stem": ".......... John .......... Mary knew the answer to the question.",
         "options": ["a) Both / and", "b) Either / or", "c) Neither / nor", "d) Not only / but also"]},
        {"stem": "He is .......... a good student .......... a talented athlete.",
         "options": ["a) either / or", "b) neither / nor", "c) not only / but also", "d) whether / or"]},
        {"stem": ".......... you agree with me .......... you don't, I will go ahead with the plan.",
         "options": ["a) Both / and", "b) Either / or", "c) Neither / nor", "d) Whether / or"]},
    ],
    "vocabulary_mcq": [
        {"stem": "A good .......... respects the law and contributes to society.",
         "options": ["a) citizen", "b) citizenship", "c) cite", "d) city"]},
        {"stem": "Voting is both a right and a .......... of every citizen.",
         "options": ["a) response", "b) responsibility", "c) responsible", "d) respond"]},
        {"stem": ".......... service means helping the community without payment.",
         "options": ["a) Voluntary", "b) Volume", "c) Volunteer", "d) Volt"]},
        {"stem": "Every citizen has certain rights and ..........",
         "options": ["a) duties", "b) debts", "c) doubts", "d) dates"]},
        {"stem": "Active participation in .......... life is important for democracy.",
         "options": ["a) civic", "b) civil", "c) civilian", "d) civilized"]},
        {"stem": "Respecting .......... is a key part of good citizenship.",
         "options": ["a) diverse", "b) diversity", "c) diversify", "d) diversion"]},
    ],
    "grammar_rewrite": [
        {"sentence": "He speaks English. He also speaks French.", "instruction": "use not only ... but also"},
        {"sentence": "She didn't call me. She didn't send a message.", "instruction": "use neither ... nor"},
        {"sentence": "You can take the bus. You can take the train.", "instruction": "use either ... or"},
        {"sentence": "The project was interesting. It was also educational.", "instruction": "use both ... and"},
        {"sentence": "He doesn't like coffee. He doesn't like tea.", "instruction": "use neither ... nor"},
        {"sentence": "She is talented. She is hardworking.", "instruction": "use not only ... but also"},
        {"sentence": "We can go to the park. We can stay at home.", "instruction": "use either ... or"},
        {"sentence": "The citizens have rights. The citizens have duties.", "instruction": "use both ... and"},
    ],
    "true_false": [
        "Citizenship only means having a passport from a country.",
        "Good citizens have both rights and responsibilities.",
        "Voting is not an important part of citizenship.",
        "Community service is a way of being a good citizen.",
        "Citizens only have duties but no rights.",
        "Respecting the law is one of the responsibilities of a citizen.",
    ],
    "rewrite_correct": [
        "Both she and her brother doesn't like sports.",
        "Neither the teacher or the students were absent.",
        "Not only he is smart, but also hardworking.",
        "Either you comes with us or you stay here.",
        "Both the food and the service was excellent.",
    ],
    "complete_sentences": [
        "Good citizenship means ..........",
        "Both rights and responsibilities are important because ..........",
        "Citizens can contribute to their community by ..........",
        "Neither violence nor hatred can ..........",
        "Not only should citizens obey the law, but they should also ..........",
    ],
    "writing_guiding": [
        "What does it mean to be a good citizen?",
        "What are the rights and duties of a citizen?",
        "How can young people contribute to their community?",
        "Why is it important to respect the law?",
        "What role does volunteering play in citizenship?",
    ],
},

# ============================================================
# Unit 10: Culture Shock - Reported Speech
# ============================================================
10: {
    "grammar_mcq": [
        {"stem": "She said that she .......... very tired.",
         "options": ["a) is", "b) was", "c) has been", "d) will be"]},
        {"stem": "He told me that he .......... the movie the day before.",
         "options": ["a) sees", "b) saw", "c) had seen", "d) will see"]},
        {"stem": "They said they .......... to Paris the following week.",
         "options": ["a) will travel", "b) would travel", "c) travel", "d) are traveling"]},
        {"stem": "She asked me where I ..........",
         "options": ["a) live", "b) lived", "c) am living", "d) will live"]},
        {"stem": "He asked me if I .......... help him with his homework.",
         "options": ["a) can", "b) could", "c) will", "d) may"]},
        {"stem": "The teacher told the students .......... quiet.",
         "options": ["a) be", "b) to be", "c) being", "d) been"]},
        {"stem": "'I am studying English,' she said. She said she .......... English.",
         "options": ["a) is studying", "b) was studying", "c) studies", "d) studied"]},
        {"stem": "He said, 'I will call you tomorrow.' He said he .......... me the next day.",
         "options": ["a) will call", "b) would call", "c) calls", "d) called"]},
        {"stem": "She asked, 'Did you enjoy the trip?' She asked me .......... I had enjoyed the trip.",
         "options": ["a) that", "b) if", "c) what", "d) when"]},
        {"stem": "The guide said, 'This temple was built 500 years ago.' The guide said that temple .......... 500 years before.",
         "options": ["a) was built", "b) had been built", "c) is built", "d) has been built"]},
    ],
    "vocabulary_mcq": [
        {"stem": ".......... shock is the feeling of confusion when living in a new culture.",
         "options": ["a) Cultural", "b) Culture", "c) Cultured", "d) Cultivate"]},
        {"stem": "It takes time to .......... to a new culture and way of life.",
         "options": ["a) adopt", "b) adapt", "c) adept", "d) adult"]},
        {"stem": "Different cultures have different customs and ..........",
         "options": ["a) traditions", "b) traditional", "c) traditionally", "d) traditionalist"]},
        {"stem": "Feeling .......... is common when you first move to a new country.",
         "options": ["a) home", "b) homesick", "c) homework", "d) homeland"]},
        {"stem": "Learning the local .......... helps reduce culture shock.",
         "options": ["a) language", "b) linguistic", "c) lingual", "d) linguist"]},
        {"stem": ".......... understanding between cultures promotes peace.",
         "options": ["a) Mutual", "b) Mute", "c) Multiple", "d) Mural"]},
    ],
    "grammar_rewrite": [
        {"sentence": "'I love learning about different cultures,' she said.", "instruction": "change into reported speech"},
        {"sentence": "'We visited the museum yesterday,' they said.", "instruction": "change into reported speech"},
        {"sentence": "'I will travel to Japan next year,' he said.", "instruction": "change into reported speech"},
        {"sentence": "'Are you enjoying your stay here?' she asked me.", "instruction": "change into reported speech"},
        {"sentence": "'Don't be afraid of trying new food,' the guide told us.", "instruction": "change into reported speech"},
        {"sentence": "'Where did you learn Arabic?' he asked her.", "instruction": "change into reported speech"},
        {"sentence": "'I have been living here for three years,' she said.", "instruction": "change into reported speech"},
        {"sentence": "'Can you help me find the hotel?' the tourist asked.", "instruction": "change into reported speech"},
    ],
    "true_false": [
        "Culture shock only affects people who travel abroad for the first time.",
        "Learning the local language can help reduce culture shock.",
        "Culture shock has several stages, including the honeymoon phase.",
        "Everyone experiences culture shock in exactly the same way.",
        "Adapting to a new culture means forgetting your own culture.",
        "Culture shock is a temporary condition that usually gets better with time.",
    ],
    "rewrite_correct": [
        "She said that she is very happy in her new country.",
        "He told me that he will visit me tomorrow.",
        "They said they have finished their project yesterday.",
        "She asked me where do I live.",
        "He said that he can help me with my homework.",
    ],
    "complete_sentences": [
        "Culture shock is ..........",
        "When people move to a new country, they often feel ..........",
        "She said that she had experienced culture shock when ..........",
        "To overcome culture shock, you should ..........",
        "He told me that different cultures ..........",
    ],
    "writing_guiding": [
        "What is culture shock?",
        "What are the stages of culture shock?",
        "How can people overcome culture shock?",
        "Have you ever experienced culture shock? Describe it.",
        "Why is it important to learn about other cultures?",
    ],
},

# ============================================================
# Unit 11: Artificial Intelligence - Linking Words
# ============================================================
11: {
    "grammar_mcq": [
        {"stem": ".......... the rain, we decided to go out for a walk.",
         "options": ["a) Because", "b) Despite", "c) Although", "d) Since"]},
        {"stem": "She studied very hard; .........., she passed the exam with flying colors.",
         "options": ["a) however", "b) therefore", "c) although", "d) despite"]},
        {"stem": "AI technology is advancing rapidly. .........., some people are worried about job losses.",
         "options": ["a) Moreover", "b) However", "c) Therefore", "d) Furthermore"]},
        {"stem": "He failed the exam .......... he had studied very hard.",
         "options": ["a) because", "b) so", "c) although", "d) therefore"]},
        {"stem": ".......... AI has many benefits, it also raises ethical concerns.",
         "options": ["a) Because", "b) However", "c) Although", "d) Therefore"]},
        {"stem": "Robots can perform dangerous tasks. .........., they can work without rest.",
         "options": ["a) However", "b) Although", "c) Furthermore", "d) Despite"]},
        {"stem": "She didn't get the job .......... having excellent qualifications.",
         "options": ["a) although", "b) because", "c) despite", "d) so"]},
        {"stem": "The experiment failed. .........., the scientists didn't give up.",
         "options": ["a) Moreover", "b) Furthermore", "c) Nevertheless", "d) Therefore"]},
        {"stem": "AI is used in medicine .......... it can analyze data faster than humans.",
         "options": ["a) although", "b) despite", "c) because", "d) however"]},
        {"stem": ".......... to the development of AI, many tasks are now automated.",
         "options": ["a) Although", "b) Despite", "c) Due", "d) However"]},
        {"stem": "He is very smart; .........., he is also very humble.",
         "options": ["a) however", "b) moreover", "c) therefore", "d) despite"]},
        {"stem": ".......... the fact that AI is useful, it cannot replace human creativity.",
         "options": ["a) Although", "b) Despite", "c) Because", "d) Therefore"]},
    ],
    "vocabulary_mcq": [
        {"stem": "Artificial .......... refers to machines that can think and learn.",
         "options": ["a) intelligent", "b) intelligence", "c) intelligently", "d) intellect"]},
        {"stem": "A .......... is a set of instructions that a computer follows to solve a problem.",
         "options": ["a) algorithm", "b) algebra", "c) allergy", "d) allegory"]},
        {"stem": ".......... learning is a type of AI where machines learn from data.",
         "options": ["a) Mechanic", "b) Machine", "c) Manual", "d) Magnetic"]},
        {"stem": "Self-driving cars are an example of .......... technology.",
         "options": ["a) automate", "b) automatic", "c) autonomous", "d) automobile"]},
        {"stem": "AI can .......... large amounts of data very quickly.",
         "options": ["a) analyze", "b) analysis", "c) analytical", "d) analyst"]},
        {"stem": ".......... are programmable machines designed to perform tasks automatically.",
         "options": ["a) Robots", "b) Robotic", "c) Robotics", "d) Robotize"]},
    ],
    "grammar_rewrite": [
        {"sentence": "AI is useful. It cannot replace human emotions.", "instruction": "join using 'although'"},
        {"sentence": "He worked very hard. He didn't get promoted.", "instruction": "join using 'despite'"},
        {"sentence": "Technology has many benefits. We should use it responsibly.", "instruction": "join using 'however'"},
        {"sentence": "AI can process data quickly. It is widely used in healthcare.", "instruction": "join using 'because'"},
        {"sentence": "Robots are efficient. They lack creativity.", "instruction": "join using 'nevertheless'"},
        {"sentence": "AI has advanced rapidly. Many jobs have been automated.", "instruction": "join using 'as a result'"},
        {"sentence": "She has a degree in computer science. She has experience in AI.", "instruction": "join using 'moreover'"},
        {"sentence": "The rain was heavy. We went out.", "instruction": "join using 'in spite of'"},
    ],
    "true_false": [
        "Artificial intelligence can completely replace human intelligence.",
        "AI is used in many fields including medicine, education, and transportation.",
        "Machine learning allows computers to learn without being explicitly programmed.",
        "AI technology only benefits large companies, not ordinary people.",
        "Self-driving cars are an application of artificial intelligence.",
        "AI raises no ethical or social concerns.",
    ],
    "rewrite_correct": [
        "Although AI is very advanced, but it cannot replace humans.",
        "Despite of the rain, we went to the park.",
        "He is very rich. Moreover, he is also very generous. He is very rich; moreover he is also very generous.",
        "Because the heavy traffic, we arrived late to the meeting.",
        "She failed the test however she studied very hard.",
    ],
    "complete_sentences": [
        "Artificial intelligence is important because ..........",
        "Although AI has many advantages, ..........",
        "Furthermore, AI technology can be used to ..........",
        "Despite the concerns about AI, ..........",
        "As a result of advances in AI, ..........",
    ],
    "writing_guiding": [
        "What is artificial intelligence?",
        "What are the advantages of AI?",
        "What are the disadvantages or risks of AI?",
        "How is AI used in everyday life?",
        "What do you think the future of AI will look like?",
    ],
},

# ============================================================
# Unit 12: Digital Literacy - Revision
# ============================================================
12: {
    "grammar_mcq": [
        {"stem": "If she .......... the email, she would have replied immediately.",
         "options": ["a) sees", "b) saw", "c) had seen", "d) has seen"]},
        {"stem": "The website .......... by millions of people every day.",
         "options": ["a) visits", "b) is visited", "c) visited", "d) visiting"]},
        {"stem": "He said that he .......... how to code.",
         "options": ["a) knows", "b) knew", "c) has known", "d) will know"]},
        {"stem": "She .......... using computers since she was five years old.",
         "options": ["a) is", "b) was", "c) has been", "d) had been"]},
        {"stem": ".......... technology is useful, we should not depend on it entirely.",
         "options": ["a) Because", "b) Although", "c) Since", "d) Due to"]},
        {"stem": "I wish I .......... more about cybersecurity.",
         "options": ["a) know", "b) knew", "c) known", "d) knowing"]},
        {"stem": "The app .......... downloaded over a million times since its release.",
         "options": ["a) is", "b) was", "c) has been", "d) had been"]},
        {"stem": "She asked me .......... I could help her with the computer.",
         "options": ["a) that", "b) if", "c) what", "d) which"]},
        {"stem": ".......... you learn digital skills .......... you will be left behind.",
         "options": ["a) Both / and", "b) Either / or", "c) Neither / nor", "d) Not only / but also"]},
        {"stem": "The new software .......... by the IT team next week.",
         "options": ["a) will be installed", "b) will install", "c) installs", "d) installed"]},
        {"stem": "He .......... his computer fixed at the repair shop.",
         "options": ["a) has", "b) had", "c) got", "d) all of these"]},
        {"stem": "She told me that she .......... buy a new laptop the following day.",
         "options": ["a) will", "b) would", "c) can", "d) is going to"]},
    ],
    "vocabulary_mcq": [
        {"stem": "Digital .......... means the ability to use technology effectively.",
         "options": ["a) literate", "b) literacy", "c) literally", "d) literature"]},
        {"stem": ".......... is the practice of protecting systems and networks from digital attacks.",
         "options": ["a) Cybersecurity", "b) Cyber", "c) Cycling", "d) Cylinder"]},
        {"stem": "Social .......... platforms connect people around the world.",
         "options": ["a) medium", "b) media", "c) mediate", "d) mediator"]},
        {"stem": "Personal .......... should be protected when using the internet.",
         "options": ["a) date", "b) data", "c) datum", "d) database"]},
        {"stem": ".......... refers to the illegal copying and distribution of software.",
         "options": ["a) Privacy", "b) Piracy", "c) Primacy", "d) Pharmacy"]},
        {"stem": "Being digitally .......... is essential in the modern world.",
         "options": ["a) liter", "b) literal", "c) literate", "d) literary"]},
    ],
    "grammar_rewrite": [
        {"sentence": "Many people use the internet every day.", "instruction": "change into passive voice"},
        {"sentence": "'I enjoy using social media,' she said.", "instruction": "change into reported speech"},
        {"sentence": "I don't know how to code.", "instruction": "begin with: I wish..."},
        {"sentence": "He speaks English. He also speaks Arabic.", "instruction": "use not only ... but also"},
        {"sentence": "She studied hard. She passed the exam easily.", "instruction": "join using 'therefore'"},
        {"sentence": "He didn't update his antivirus. His computer got a virus.", "instruction": "use third conditional"},
        {"sentence": "A technician repaired her laptop.", "instruction": "rewrite using causative (have)"},
        {"sentence": "Technology has benefits. It also has risks.", "instruction": "join using 'although'"},
    ],
    "true_false": [
        "Digital literacy is only about knowing how to use social media.",
        "Cybersecurity helps protect personal information online.",
        "Everyone in the world has equal access to digital technology.",
        "Strong passwords help protect online accounts from hackers.",
        "It is safe to share personal information on any website.",
        "Digital literacy includes the ability to evaluate online information critically.",
    ],
    "rewrite_correct": [
        "The internet is use by billions of people around the world.",
        "She said that she will learn coding next month.",
        "I wish I can use advanced computer software.",
        "Neither he or his brother knows how to fix the computer.",
        "Despite she was tired, she continued working on the project.",
    ],
    "complete_sentences": [
        "Digital literacy is important because ..........",
        "To stay safe online, you should ..........",
        "Social media can be beneficial when ..........",
        "If everyone had access to technology, ..........",
        "She said that digital skills are necessary for ..........",
    ],
    "writing_guiding": [
        "What is digital literacy?",
        "Why is digital literacy important in the modern world?",
        "What are the risks of using the internet?",
        "How can people protect themselves online?",
        "How has technology changed education?",
    ],
},

}  # End of GRAMMAR_BANK
